theme: jekyll-theme-slate
title: taxonomy working file
description: a way to demonstate how taxonomy will display across all categories, subcategories, PLPs
.
<div id='table-container'></div>
.
 
<script>
  CsvToHtmlTable.init({
    csv_path: 'data/countries.csv',
    element: 'table-container', 
    allow_download: true,
    csv_options: {separator: ';', delimiter: '"'},
    datatables_options: {"paging": false}
  });
</script>
