<!DOCTYPE html>

<html>

<body>
theme: jekyll-theme-slate
title: taxonomy working file
description: a way to demonstate how taxonomy will display across all categories, subcategories, PLPs




<?php

ECHO "Hello World!<br>";

echo "Hello World!<br>";

EcHo "Hello World!<br>";

?>



</body>

</html>
